# Generated by Django 2.2.2 on 2019-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190905_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='../images/'),
        ),
    ]
