# Generated by Django 2.2.2 on 2019-09-05 18:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190905_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='../media/photos'), upload_to=''),
        ),
    ]
