# Generated by Django 2.2.2 on 2019-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190906_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(height_field=70, upload_to='images/', width_field=70),
        ),
    ]
