# Generated by Django 2.2.2 on 2019-09-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190906_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatalogItem_name', models.CharField(default='', max_length=60)),
                ('CatalogItem_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='product_image',
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(default='', max_length=60)),
                ('catalog_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.CatalogItem')),
            ],
        ),
    ]
