# Generated by Django 2.2.2 on 2019-09-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20190907_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='Catalog_id',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='CatalogItem_id',
        ),
    ]
