# Generated by Django 2.2.2 on 2019-09-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190907_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_catalogId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_catalogItemId',
        ),
    ]
