# Generated by Django 2.2.2 on 2019-09-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190907_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='CatalogItem_image',
            new_name='catalogItem_image',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='CatalogItem_name',
            new_name='catalogItem_name',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='CatalogItem_products',
            new_name='catalogItem_products',
        ),
    ]
