# Generated by Django 2.2.2 on 2019-09-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20190907_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='catalogItem_products',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='catalogItem_catalog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Catalog'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
    ]
