# Generated by Django 2.2.2 on 2019-09-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20190907_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='catalog_items',
        ),
        migrations.AddField(
            model_name='product',
            name='product_catalogItems',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.CatalogItem'),
        ),
    ]
