# Generated by Django 2.2.2 on 2019-09-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20190907_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogItem',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catalogItem_catalog',
            new_name='category_catalog',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catalogItem_image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catalogItem_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_catalogItems',
            new_name='product_categories',
        ),
    ]
