# Generated by Django 2.2.2 on 2019-09-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
