# Generated by Django 2.2.2 on 2019-09-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20190907_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(upload_to='images/')),
                ('category_catalog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(default='', max_length=60)),
                ('product_descr', models.CharField(default='', max_length=200)),
                ('product_price', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
    ]
