# Generated by Django 2.2.2 on 2019-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_catalog_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
