# Generated by Django 2.2.2 on 2019-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_best',
            field=models.BooleanField(default=False),
        ),
    ]
