# Generated by Django 2.2.2 on 2019-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_product_product_best'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_descr',
            new_name='product_descr_short',
        ),
        migrations.AddField(
            model_name='product',
            name='product_descr_full',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
