# Generated by Django 2.2.2 on 2019-09-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20190917_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charact_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_descr_full',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(default='', max_length=200)),
                ('property_text', models.CharField(default='', max_length=200)),
                ('property_charact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Charact')),
            ],
        ),
        migrations.AddField(
            model_name='charact',
            name='property_categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
    ]
