# Generated by Django 2.2.2 on 2019-09-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20190918_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charact',
            old_name='property_categories',
            new_name='Charact_product',
        ),
    ]
