# Generated by Django 2.2.2 on 2019-09-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20190918_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charact',
            old_name='Charact_product',
            new_name='charact_product',
        ),
        migrations.RenameField(
            model_name='charact',
            old_name='charact_name',
            new_name='charact_title',
        ),
        migrations.AddField(
            model_name='charact',
            name='charact_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
